name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x ./server_springBoot/portfolio/gradlew

      - name: Build Spring Boot app
        run: |
          cd ./server_springBoot/portfolio
          ./gradlew build -x test --no-daemon --info

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/React_QbixPortfolio
            git pull origin main
            cd server_springBoot/portfolio
            ./gradlew build -x test --no-daemon --info
            sudo systemctl restart portfolio
